[package]
name = "isahc"
version = "0.9.2"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client", "async", "curl"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/isahc"
documentation = "https://docs.rs/isahc/"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
features = ["cookies", "json"]

[badges.maintenance]
status = "actively-developed"

[features]
default = ["http2", "static-curl", "text-decoding"]
cookies = ["chrono"]
http2 = ["curl/http2"]
json = ["serde", "serde_json"]
psl = ["parking_lot", "publicsuffix"]
spnego = ["curl-sys/spnego"]
static-curl = ["curl/static-curl"]
text-decoding = ["encoding_rs", "mime"]
middleware-api-preview = []
static-ssl = ["curl/static-ssl", "curl/force-system-lib-on-osx"]

[dependencies]
bytes = "0.5"
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
curl = "0.4.25"
curl-sys = "0.4.26"
futures-channel = "0.3"
futures-io = "0.3"
http = "0.2"
lazy_static = "1"
log = "0.4"
slab = "0.4"
sluice = "0.5"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.encoding_rs]
version = "0.8"
optional = true

[dependencies.futures-util]
version = "0.3"
default-features = false
features = ["io"]

[dependencies.mime]
version = "0.3"
optional = true

[dependencies.parking_lot]
version = "0.10"
optional = true

[dependencies.publicsuffix]
version = "1.5"
default-features = false
optional = true

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dev-dependencies]
env_logger = "0.7"
flate2 = "1.0"
futures = "0.3"
indicatif = "0.14"
mockito = "0.25"
rayon = "1"
speculate = "0.1"
static_assertions = "1.1"
structopt = "0.3"

[[example]]
name = "json"
required-features = ["json", "serde/derive"]

[workspace]
members = ["benchmarks"]
