[package]
name = "isahc"
version = "0.6.0"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client", "async", "curl"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/isahc"
documentation = "https://docs.rs/isahc/"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges.maintenance]
status = "actively-developed"

[features]
default = ["cookies", "http2", "static-curl"]
cookies = ["chrono"]
http2 = ["curl/http2"]
json = ["serde", "serde_json"]
nightly = []
psl = ["parking_lot", "publicsuffix"]
static-curl = ["curl/static-curl"]
middleware-api = []

[dependencies]
bytes = "0.4"
crossbeam-channel = "0.3"
curl = "^0.4.20"
curl-sys = "^0.4.20"
futures-io-preview = "=0.3.0-alpha.17"
http = "0.1"
lazy_static = "1"
log = "0.4"
slab = "0.4"
sluice = "0.4"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.futures-util-preview]
version = "=0.3.0-alpha.17"
features = ["io"]

[dependencies.parking_lot]
version = "0.9"
optional = true

[dependencies.publicsuffix]
version = "1.5"
default-features = false
optional = true

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dev-dependencies]
env_logger = "0.6"
futures-preview = "=0.3.0-alpha.17"
mockito = "0.20"
rayon = "1"
speculate = "0.1"

[[example]]
name = "async"
required-features = ["nightly"]

[workspace]
members = ["benchmarks"]
