[package]
name = "isahc-benchmarks"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.isahc]
path = ".."

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"
rayon = "1"
reqwest = "0.9"
rouille = "3"

[[bench]]
name = "download"
harness = false
